title: Rotation Solver Reborn
description: FFXIV Combat Automation Plugin - Documentation & Changelog
theme: jekyll-theme-cayman
show_downloads: false
github:
  repository_url: https://github.com/FFXIV-CombatReborn/RotationSolverReborn
  is_project_page: true
